remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: *winterreise_rt*: a subset of Schubert Winterreise Dataset(SWD) for real-time lyrics alignment

email: june@kaist.ac.kr
